# Site settings
title: 山柚的博客
SEOTitle: 山柚的博客 | Arithmeticsx Blog
header-img: img/header_mini.png
email: arithmeticsx@gmail.com
description: "要有情 要有趣 要有才"
keyword: "arithmeticsx, Arithmeticsx Blog, 山柚， 山柚的博客， 编程， 投资， 生活"
url: "http://arithmeticsx.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/arithmeticsx/arithmeticsx.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Be to you want to be!"
sidebar-avatar: /img/header.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     东小山大王
zhihu_username:     山柚
# github_username:    arithmeticsx
# facebook_username:  arithmeticsx
# jianshu_username:   arithmeticsx
# twitter_username:   arithmeticsx




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 944d97475f21442d2ad3                            #生成的clientID
  clientSecret: 6e4e89ddba07d3d1275b79045b7b9485380418b8    #生成的clientSecret
  repo: arithmeticsx.github.io    #仓库名称
  owner: arithmeticsx    #github用户名
  admin: arithmeticsx
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: bc635c6c248dd16e3d4deed0a1aab3df

# Google Analytics
ga_track_id: 'UA-148564395-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "arithmeticsx github",
        href: "https://github.com/arithmeticsx"
    },{
        title: "东小山大王的微博",
        href: "https://weibo.com/royalisme"
    },{
        title: "山柚的知乎",
        href: "https://www.zhihu.com/people/royalisme/activities"
    }
]
